# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameover',
            field=models.BooleanField(default=False),
        ),
    ]
