# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai',
            field=models.BooleanField(default=False),
        ),
    ]
